[tool.poetry]
name = "ml-lib"
version = "0.1.0"
description = ""
authors = ["oltremare <oncwnuHZnY0Uo1jEvpEs9s-sZa78@git.weixin.qq.com>"]
readme = "README.md"
packages = [
    { include = "ml-lib" }
]

[tool.poetry.dependencies]
python = "^3.11"
kaggle = "^1.6.12"
keras = "^3.3.3"
tensorflow = "^2.16.1"
scikit-learn = "^1.4.2"
pyyaml = "^6.0.1"
seaborn = "^0.13.2"
gdown = "^5.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
