loss_function: 'binary_crossentropy'
optimizer: 'adam'
sequence_length: 200
batch_train: 5000
batch_test: 5000
categories:
  - 'phishing'
  - 'legitimate'
char_index: None
epoch: 1
embedding_dimension: 50
