name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Parse version info from tag
      run: |
        VERSION=${GITHUB_REF:11}
        echo "version=$VERSION" >> $GITHUB_ENV
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Configure package repository
      run: |
        poetry config repositories.test-pypi https://test.pypi.org/legacy/
        poetry config pypi-token.test-pypi ${{ secrets.TEST_PY_TOKEN }}
    - name: Bump poetry version
      run: poetry version ${{ env.version }}
    - name: Build and publish
      run: |
        poetry build
        poetry publish